# Generated by Django 3.1.1 on 2020-10-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='grade',
        ),
        migrations.AddField(
            model_name='homework',
            name='group',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
