# Generated by Django 3.1.1 on 2020-10-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='group_id',
            new_name='group_grade',
        ),
    ]
