# Generated by Django 3.1.1 on 2020-10-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
