# Generated by Django 3.1 on 2020-09-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
