# Generated by Django 3.1.1 on 2020-10-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student_username',
        ),
    ]
